/**:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        robot1_rail_joint:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 0.5
        robot1_joint_1_s:
          has_velocity_limits: true
          max_velocity: 3.665
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot1_joint_2_l:
          has_velocity_limits: true
          max_velocity: 3.665
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot1_joint_3_u:
          has_velocity_limits: true
          max_velocity: 4.625
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot1_joint_4_r:
          has_velocity_limits: true
          max_velocity: 7.330
          has_acceleration_limits: true
          max_acceleration: 3.0
        robot1_joint_5_b:
          has_velocity_limits: true
          max_velocity: 7.330
          has_acceleration_limits: true
          max_acceleration: 3.0
        robot1_joint_6_t:
          has_velocity_limits: true
          max_velocity: 15.450
          has_acceleration_limits: true
          max_acceleration: 5.0

        robot1_left_finger_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5
        robot1_right_finger_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5

        robot2_joint_1_s:
          has_velocity_limits: true
          max_velocity: 3.665
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot2_joint_2_l:
          has_velocity_limits: true
          max_velocity: 3.665
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot2_joint_3_u:
          has_velocity_limits: true
          max_velocity: 4.625
          has_acceleration_limits: true
          max_acceleration: 2.0
        robot2_joint_4_r:
          has_velocity_limits: true
          max_velocity: 7.330
          has_acceleration_limits: true
          max_acceleration: 3.0
        robot2_joint_5_b:
          has_velocity_limits: true
          max_velocity: 7.330
          has_acceleration_limits: true
          max_acceleration: 3.0
        robot2_joint_6_t:
          has_velocity_limits: true
          max_velocity: 15.450
          has_acceleration_limits: true
          max_acceleration: 5.0
