/**:
  ros__parameters:
    robot1_gp25_arm:
      kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.5
      kinematics_solver_attempts: 10

    robot2_gp25_welder_arm:
      kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.5
      kinematics_solver_attempts: 10
