/**:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - robot1_arm_controller
        - gripper_controller
        - robot2_arm_controller

      robot1_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - robot1_rail_joint
          - robot1_joint_1_s
          - robot1_joint_2_l
          - robot1_joint_3_u
          - robot1_joint_4_r
          - robot1_joint_5_b
          - robot1_joint_6_t

      gripper_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - robot1_left_finger_joint
          - robot1_right_finger_joint

      robot2_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - robot2_joint_1_s
          - robot2_joint_2_l
          - robot2_joint_3_u
          - robot2_joint_4_r
          - robot2_joint_5_b
          - robot2_joint_6_t
